[package]
name = "etherscan"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.21"
reqwest = {version = "0.11", features = ["json"]}
serde = {version = "1.0.136", default-features = false, features = ["derive"]}
serde_plain = "1.0"
web3 = "0.18.0"
